services:
  - type: web
    name: decentralized-notebook-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: notebook-db
          property: connectionString

databases:
  - name: notebook-db
